import ModalAdd from '@/components/Modals/ModalAdd';
import List from '@/components/Todo/List';
import Activity from '@/components/Todo/TodoEmpty';
import { AlertContext } from '@/context/AlertContext';
import { IsAddContext } from '@/context/IsAddContext';
import {
  Alert,
  AlertIcon,
  Box,
  Button,
  Container,
  FormControl,
  Icon,
  Input,
  Text,
  useDisclosure,
} from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useContext, useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { AiOutlinePlus } from 'react-icons/ai';
import { IoIosArrowBack } from 'react-icons/io';
import { TbPencil } from 'react-icons/tb';

const DetailsActivity = () => {
  const router = useRouter();
  const activityId = router.query.id;
  const [result, setResult] = useState(null);
  const [edit, setEdit] = useState(false);
  const [isAdd] = useContext(IsAddContext);
  const [isDelete] = useContext(AlertContext);

  const modalAdd = useDisclosure();
  const { register, watch, setValue } = useForm();

  useEffect(() => {
    fetch(`https://todo.api.devcode.gethired.id/activity-groups/${activityId}`)
      .then(res => res.json())
      .then(data => {
        setResult(data);
        setValue('title', data?.title);
      });
  }, [isAdd, activityId, setValue, isDelete, setResult]);

  const onSubmit = () => {
    const data = {
      title: watch('title'),
    };

    updateTitle(activityId, data);
  };

  return (
    <>
      <Head>
        <title>Todo List App - {result?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container data-cy="new-activity" maxW={['100%', '100%', '1000px']}>
        {isDelete && (
          <Box data-cy="modal-information" pt={3}>
            <Alert data-cy="modal-information" status="success" variant="solid">
              <AlertIcon />
              Delete task success!
            </Alert>
          </Box>
        )}
        <Box
          my={8}
          display="flex"
          justifyContent={'space-between'}
          alignItems="center"
        >
          <Box display="flex" alignItems="center" gap={4}>
            <Icon
              as={IoIosArrowBack}
              w={6}
              h={6}
              onClick={() => router.back()}
            />

            <FormControl display={'flex'} alignItems="center">
              <Box data-cy="todo-title">
                <Input
                  {...register('title')}
                  type={'text'}
                  fontWeight="bold"
                  fontSize={'3xl'}
                  variant={edit ? 'outline' : 'unstyled'}
                  onBlur={onSubmit}
                />
              </Box>

              <Button
                onClick={() => setEdit(!edit)}
                variant={'unstyled'}
                display="flex"
                alignItems={'center'}
              >
                <Icon as={TbPencil} w={6} h={6} color="#C4C4C4" />
              </Button>
            </FormControl>
          </Box>

          <Button
            data-cy="todo-add-button"
            onClick={modalAdd.onOpen}
            leftIcon={<AiOutlinePlus color="white" />}
            background="#16ABF8"
            color="white"
            _hover={{ bg: '#16ABF8' }}
            size="lg"
            borderRadius={'3xl'}
          >
            <Text>Tambah</Text>
          </Button>
        </Box>

        {result?.todo_items?.length > 0 ? (
          <Box>
            {result?.todo_items?.map((item, key) => (
              <Box key={key} data-cy="list-item">
                <List
                  title={item?.title}
                  priority={item.priority}
                  id={item.id}
                  is_active={item.is_active}
                />
              </Box>
            ))}
          </Box>
        ) : (
          <Activity />
        )}
      </Container>

      <ModalAdd
        isOpen={modalAdd.isOpen}
        onClose={modalAdd.onClose}
        groupId={result?.id}
        type="create"
      />
    </>
  );
};

export default DetailsActivity;

export async function updateTitle(id, data) {
  const response = await fetch(
    `https://todo.api.devcode.gethired.id/activity-groups/${id}`,
    {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    }
  );

  if (!response.ok) {
    throw new Error(response.statusText);
  }

  return await response.json;
}
